name: Deploy HTML

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Push Docker
        run: |
          docker build -t jagratsingh/html-test .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push jagratsingh/html-test

      - name: Run Ansible
        run: |
          ansible-playbook -i hosts.ini deploy.yaml
